import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
// @ts-ignore
import { css } from "no-stitches/runtime";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyClass = css({
  color: "green",
  backgroundColor: "white",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mode = cookies().get("mode");
  return (
    <html
      lang="en"
      // className={mode?.value === "dark" ? darkThemeClass : lightThemeClass}
    >
      <body className={`${inter.className} ${bodyClass()}`}>{children}</body>
    </html>
  );
}
